# Generated by Django 2.0.3 on 2018-04-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0003_auto_20180402_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
