# Generated by Django 2.0.3 on 2018-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_app', '0004_auto_20180402_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
